CREATE TABLE  "BMART_USERS" 
   (	"USER_ID" NUMBER, 
	"USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"PASSWORD_HASH" VARCHAR2(255) NOT NULL ENABLE, 
	"IS_MANAGER" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	 CHECK (is_manager IN ('Y', 'N')) ENABLE, 
	 CHECK (is_active IN ('Y', 'N')) ENABLE, 
	 PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("USERNAME")
  USING INDEX  ENABLE
   )
/

CREATE OR REPLACE TRIGGER  "BMART_USERS_BI_TRG" 
BEFORE INSERT ON bmart_users
FOR EACH ROW
BEGIN
    IF :NEW.user_id IS NULL THEN
        SELECT bmart_users_seq.NEXTVAL INTO :NEW.user_id FROM dual;
    END IF;
END;

/
ALTER TRIGGER  "BMART_USERS_BI_TRG" ENABLE
/