CREATE TABLE  "BMART_CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(10) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(10) NOT NULL ENABLE, 
	"PHONE_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"CITY" VARCHAR2(10) NOT NULL ENABLE, 
	"STREET" VARCHAR2(15) NOT NULL ENABLE, 
	 CONSTRAINT "BMART_CUST_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("PHONE_NUMBER")
  USING INDEX  ENABLE
   )
/
