CREATE TABLE  "BMART_PRICE_CHANGE_HISTORY" 
   (	"PRODUCT_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"CHANGE_DATE" DATE, 
	"UNIT_PRICE" NUMBER(6,2) NOT NULL ENABLE, 
	 CONSTRAINT "BMART_PRICE_HIST_PK" PRIMARY KEY ("PRODUCT_ID", "CHANGE_DATE")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "BMART_PRICE_CHANGE_HISTORY" ADD CONSTRAINT "BMART_PRICE_HIST_PROD_ID_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES  "BMART_PRODUCTS" ("PRODUCT_ID") ENABLE
/
