CREATE TABLE  "BMART_PRODUCT_CATEGORIES" 
   (	"CATEGORY_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(200), 
	 CONSTRAINT "BMART_PROD_CAT_PK" PRIMARY KEY ("CATEGORY_ID")
  USING INDEX  ENABLE
   )
/
