CREATE TABLE  "BMART_PRODUCTS" 
   (	"PRODUCT_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(40) NOT NULL ENABLE, 
	"CATEGORY_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"UNIT_PRICE" NUMBER(6,2) NOT NULL ENABLE, 
	"LAST_UPDATED_PRICE_DATE" DATE DEFAULT SYSDATE, 
	"DESCRIPTION" VARCHAR2(200) DEFAULT '-', 
	"PRODUCT_CODE_UK" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "BMART_PROD_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("PRODUCT_CODE_UK")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "BMART_PRODUCTS" ADD CONSTRAINT "BMART_PROD_CAT_FK" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES  "BMART_PRODUCT_CATEGORIES" ("CATEGORY_ID") ENABLE
/