CREATE TABLE  "BMART_TRANSACTION_LINES" 
   (	"TRANSACTION_ID" NUMBER(7,0) NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"QUANTITY" NUMBER(2,0) NOT NULL ENABLE, 
	"TOTAL_LINE_AMOUNT" NUMBER(10,2) NOT NULL ENABLE, 
	 CONSTRAINT "BMART_TRANS_LINE_PK" PRIMARY KEY ("TRANSACTION_ID", "PRODUCT_ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "BMART_TRANSACTION_LINES" ADD CONSTRAINT "BMART_TRANS_LINE_PROD_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES  "BMART_PRODUCTS" ("PRODUCT_ID") ENABLE
/
ALTER TABLE  "BMART_TRANSACTION_LINES" ADD CONSTRAINT "BMART_TRANS_LINE_TRANS_FK" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES  "BMART_TRANSACTIONS" ("TRANSACTION_ID") ENABLE
/
