CREATE TABLE  "BMART_TRANSACTIONS" 
   (	"TRANSACTION_ID" NUMBER(7,0) NOT NULL ENABLE, 
	"TRANS_DATE" DATE DEFAULT SYSDATE, 
	"TOTAL_AMOUNT" NUMBER(15,2), 
	"COMMENTS" VARCHAR2(300), 
	"CUSTOMER_ID" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "BMART_TRANS_PK" PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "BMART_TRANSACTIONS" ADD CONSTRAINT "BMART_TRANS_CUST_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES  "BMART_CUSTOMERS" ("CUSTOMER_ID") ENABLE
/
